[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.18"

[features]
seeds = false
skip-lint = false

[programs.devnet]
solana-oft = "5X3zucEv9LCpVYFr9ezHBXpFFy4w8Wr83nHCQK9tkvVe"

[programs.localnet]
solana-vault = "9shwxWDUNhtwkHocsUAmrNAQfBH2DHh4njdAEdHZZkF2"
uln = "CduQbgrsyGupNemhnwQhtQjqBkawJk4pFx3axQLGg4bL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
deposit_vault = "yarn run ts-node scripts/05deposit_vault.ts"
init_oapp = "yarn run ts-node scripts/02init_oapp.ts"
oft = "yarn run ts-node scripts/oft.ts"
order_delivery = "yarn run ts-node scripts/set_order_delivery.ts"
print_pda = "yarn run ts-node scripts/00print_pda.ts"
quote_deposit = "yarn run ts-node scripts/quote_oapp.ts"

send_oapp = "yarn run ts-node scripts/send.ts"
set_broker = "yarn run ts-node scripts/set_broker.ts"
set_token = "yarn run ts-node scripts/set_token.ts"
set_account_list = "yarn run ts-node scripts/set_account_list.ts"
setconfig_oapp = "yarn run ts-node scripts/03setconfig_oapp.ts"
setup_oapp = "yarn run ts-node scripts/01setup_oapp.ts"
setup_vault = "yarn run ts-node scripts/04setup_vault.ts"
reset_lz_types = "yarn run ts-node scripts/reset_lz_receive_types.ts"
reinit_lz_types = "yarn run ts-node scripts/reinit_lz_receive_types.ts"
print_config = "yarn run ts-node scripts/print_config.ts"
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "76y77prsiCMvXMjuoZ5VRrhG5qYBrUMYTE5WgHqgjEn6"
program = "endpoint.so"

[[test.genesis]]
address = "7a4WjyR8VZ7yZz5XJAKm39BUGn5iT9CKcv2pmG9tdXVH"
program = "uln.so"

[test.validator]
bind_address = "127.0.0.1"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"